#!/bin/bash
#
# Copyright (c) Authors: https://www.armbian.com/authors
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# truncate, save and clean logs if they get over 75% of the /var/log size
# working only when armbian-ramlog is enabled

TRESHOLD=75 # %
JOURNAL_SIZE=5M # size to shrink systemd-journal

[ -f /etc/default/ramlog-oe ] && . /etc/default/ramlog-oe
[ "$ENABLED" != true ] && exit 0

logusage=$(df /var/log/ --output=pcent | tail -1 |cut -d "%" -f 1)
if [ $logusage -ge $TRESHOLD ]; then
    # write to SD
    /usr/lib/ramlog-oe/ramlog-oe write >/dev/null 2>&1
    # rotate logs on "disk"
    /usr/sbin/logrotate --force /etc/logrotate.conf
    # truncate
    /usr/bin/find /var/log -name '*.log' -or -name '*.xz' -or -name 'lastlog' -or -name 'messages' -or -name 'debug' -or -name 'syslog' | xargs --no-run-if-empty truncate --size 0
    /usr/bin/find /var/log -name 'btmp' -or -name 'wtmp' -or -name 'faillog' -or -name 'firewalld' | xargs --no-run-if-empty truncate --size 0
    /usr/bin/find /var/log -name 'mail.err' -or -name 'mail.info' -or -name 'mail.warning' | xargs --no-run-if-empty truncate --size 0
    # remove
    /usr/bin/find /var/log -name '*.[0-9]' -or -name '*.gz' | xargs --no-run-if-empty rm --force
    # vacuum systemd-journald
    [ -d /var/log/journal ] && journalctl --vacuum-size=${JOURNAL_SIZE}
fi
